# Generated by Django 2.1.7 on 2019-08-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(max_length=8, unique=True, verbose_name='基站名')),
                ('databytes', models.SmallIntegerField()),
                ('utime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
