# Generated by Django 2.1.8 on 2019-05-05 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('e_time', models.DateTimeField(auto_now=True, verbose_name='编辑时间')),
                ('base_byte', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(max_length=8, unique=True)),
                ('ipaddr', models.GenericIPAddressField(default='127.0.0.1')),
                ('ports', models.CharField(max_length=10, null=True, unique=True)),
                ('ostype', models.CharField(default='client', max_length=10)),
                ('rate', models.CharField(default='1s', max_length=3)),
                ('status', models.IntegerField(default='0')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='basename',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devmanage.Ip', to_field='basename'),
        ),
    ]
