# Generated by Django 2.1.7 on 2019-08-14 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lendata', models.SmallIntegerField(default=0, verbose_name='字节数')),
                ('utime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='basename',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='id',
        ),
        migrations.AlterField(
            model_name='ip',
            name='basename',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='status',
            field=models.CharField(default='OFF', max_length=3),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AddField(
            model_name='datas',
            name='basename',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devmanage.Ip'),
        ),
    ]
