# Generated by Django 2.1.7 on 2019-08-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devmanage', '0002_auto_20190814_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datas',
            name='id',
        ),
        migrations.AlterField(
            model_name='datas',
            name='basename',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='devmanage.Ip'),
        ),
    ]
