# Generated by Django 2.1.7 on 2019-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devmanage', '0003_auto_20190815_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='basename',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='基站名'),
        ),
    ]
