# Generated by Django 2.1.7 on 2019-08-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devmanage', '0004_auto_20190815_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datas',
            name='basename',
            field=models.CharField(max_length=8, verbose_name='基站名'),
        ),
    ]
